### ISSUE TITLE
The todo-lib library handles client things

### ISSUE THREAD

**Issue by tilmanmixyz** [Kanavaar/todo-rs#2]
The todo-lib crate should work as a library and an abstraction on the json file, it should also be cross interface meaning CLI, GUI and TUI, but it prints things like errors and confirmation messangen to stdout, when it should return Result<>'s the Client (src/main.rs) should handle.

This design makes it impossible to use this library for GUI or TUI apps nor does it allow to use different terminal color crates, error colors or error formats.

It also calls unwrap() a bunch of times.

**Comment by Kanavaar** [comment]
wontfix because move to codeberg
